name: Deploy

on: 
  push:
    tags:
      - 'v*'

jobs:
  deploy_to_live:
    name: Publish to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn
        run: npm install yarn@latest -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Run test
        run: yarn test
      - name: Authenticate with registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/repo/.npmrc
      - name: Run publish
        run: npm publish
