name: Deploy

on: 
  push:
    tags:
      - 'v*'

jobs:
  build-test-publish:
    name: Lint,  Test, Build, and Publish to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Install yarn
        run: npm install yarn@latest -g
      - name: Install dependencies
        run: yarn
      - name: Update package-lock.json
        run: npm update
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
      - name: Run CI
        run: npm ci
      - name: Run publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
